---
platform: linux

inputs:
- name: ci
- name: env

outputs:
- name: built-acceptance-test-configs

params:
  CONFIGS:
  ENVS:
  WITH_ISOSEG: false
  WITH_DYNAMIC_ASG: false

run:
  path: ci/shared/tasks/build-acceptance-test-configs/task.bash
