---
platform: linux

inputs:
  - name: ci
  - name: repo
  - name: blob

outputs:
  - name: bumped-repo

params:
  BOSH_BLOB_PATH:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_ASSUME_ROLE_ARN:

run:
  path: ci/shared/tasks/bump-bosh-blobs/task.bash
