---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: deployments-diego
  - name: diego-ci

params:
  DEPLOYMENT_DIR: ~
  NAME: EMPTY

run:
  path: diego-ci/tasks/bosh_urc
