---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: diego-ci
- name: cf-deployment
- name: cf-deployment-diego

outputs:
- name: merged-cf-deployment

run:
  path: diego-ci/tasks/cf_deployment_tests
