---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: garden-runc-release-tarball
  - name: garden-runc-release-master
  - name: diego-ci

outputs:
  - name: garden-runc-release

run:
  path: diego-ci/concourse/checkout_garden
