platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: diego-release
  - name: diego-ci

run:
  path: diego-ci/tasks/check_expired_certs_in_diego_release

params:
  CERT_DIRECTORY:
