---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: diego-ci
- name: deployments-diego

run:
  path: diego-ci/tasks/check_for_unused_gcp_resources

params:
  SLACK_URL: ~
