platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: deployments-diego
  - name: diego-ci

run:
  path: diego-ci/tasks/check_expired_certs
