---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: diego-release
  - name: garden-runc-release-master
  - name: diego-ci

run:
  path: diego-ci/concourse/compare_garden_releases
