---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: diego-release
  - name: diego-ci
  - name: version

outputs:
  - name: created-diego-release

run:
  path: diego-ci/concourse/create_diego_dev_release
