---
platform: linux

inputs:
- name: diego-ci
- name: diego-release

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

params:
  GITHUB_TOKEN: ~
  LABEL: ~
  TITLE: ~
  DESCRIPTION: ~
  BRANCH: ~

run:
  path: diego-ci/tasks/create_diego_pr
