---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

params:
  DATADOG_API_KEY:
  STATE:
  ENVIRONMENT:
  DEPLOYMENT:

inputs:
  - name: diego-ci

run:
  path: sh
  args:
    - -c
    - |
      diego-ci/concourse/emit-datadog-deploy-event $STATE $ENVIRONMENT $DEPLOYMENT
