---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: latest

inputs:
  - name: deployments-diego
  - name: diego-ci
outputs:
  - name: deployment-vars

params:
  DEPLOYMENT_NAME: ~
  SYSTEM_DOMAIN: ~
  ENV_NAME: ~

run:
  path: diego-ci/tasks/generate-deployment-vars
