---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: deployments-diego
  - name: diego-ci
outputs:
  - name: deployment-vars

params:
  DEPLOYMENT_NAME: ~
  SYSTEM_DOMAIN: ~
  ENV_NAME: ~

run:
  path: diego-ci/tasks/generate-deployment-vars
