---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline
    tag: latest

inputs:
  - name: release
  - name: diego-ci
  - name: indicator-verification-linux
  - name: deployment-vars

params:
  ORG: INDICATORS-TEST
  SPACE: INDICATORS-TEST
  RUNAWAY_QUOTA: runaway

run:
  path: diego-ci/tasks/indicator_verification
