---
platform: windows

inputs:
  - name: diego-ci

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - diego-ci/tasks/install-golang-windows.ps1

params:
  GO_VERSION: ~
