---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: diego-ci
- name: cf-deployment-develop

outputs:
- name: merged-cf-deployment

params:
  PRIVATE_KEY:

run:
  path: diego-ci/tasks/merge_into_cf_deployment_diego
