---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: diego-ci
- name: cf-deployment
- name: cf-deployment-diego

outputs:
- name: merged-cf-deployment

run:
  path: diego-ci/tasks/merge_cf_deployment
