---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline
    tag: latest

inputs:
  - name: diego-ci
  - name: deployment-vars

params:
  ORG: INDICATORS-TEST-ORG
  SPACE: INDICATORS-TEST-SPACE
  APP_NAME: INDICATORS-TEST-APP
  RUNAWAY_QUOTA: INDICATORS-TEST-QUOTA-RUNAWAY
  RUNAWAY_MEMORY: 100G

run:
  path: diego-ci/tasks/prepare_indicator_verification
