---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: diego-ci
  - name: diegocanarywindowsapp

params:
  API: ~
  ORG: ~
  PASSWORD: ~
  SPACE: ~
  USER: ~
  APP_NAME: ~
  APP_PATH: ~
  INSTANCE_COUNT: ~
  STACK_NAME: ~

run:
  path: diego-ci/tasks/push_canary_windows_app

