---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: deployments-diego
- name: grace-config

outputs:
- name: updated-deployments-diego

run:
  path: sh
  args:
  - -c
  - |
    checksum=$(jq .grace_tarball_checksum ./grace-config/grace-config.json)

    cp -a deployments-diego updated-deployments-diego

    cat <<HERE > updated-deployments-diego/deployments-diego/vars/grace-config-vars.yml
    grace_tarball_checksum: ${checksum}
    HERE

    cd updated-deployments-diego/deployments-diego/

    echo "----- Set git identity"
    git config user.email "cf-diego@pivotal.io"
    git config user.name "CI (Automated)"

    echo "----- Update grace checksum"
    git add -A
    git commit -m "Update grace checksum"

    echo "----- DEBUG: show the commit we just created"
    git --no-pager show HEAD
