---
platform: linux

inputs:
- name: ci
- name: repo
- name: envoy-binary
outputs:
- name: bumped-repo

params:
  AWS_SECRET_ACCESS_KEY:
  AWS_ACCESS_KEY_ID:

run:
  path: ci/diego-release/tasks/bump-dependencies-envoy/task.bash
