---
platform: linux

inputs:
- name: config
- name: ci
- name: cf-volume-services-acceptance-tests

params:
  CONFIG_FILE_PATH: config/volume-services-acceptance-tests.json
  PARALLEL_NODES:
  TEST_DOCKER_PORA: false
  TEST_MOUNT_FAIL_LOGGING: false
  TEST_MOUNT_OPTIONS: false
  TEST_MULTI_CELL: false
  TEST_READ_ONLY: false

run:
  path: ci/shared/tasks/run-volume-services-acceptance-tests/task.bash
