---
platform: linux

inputs:
  - name: ci
  - name: repo
  - name: version

outputs:
  - name: created-release-tarball

params:
  GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY:
  AWS_SECRET_ACCESS_KEY:
  AWS_ACCESS_KEY_ID:
  AWS_ASSUME_ROLE_ARN:

run:
  path: ci/shared/tasks/bosh-create-release/task.bash
