---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: us-central1-docker.pkg.dev/cf-diego-pivotal/tas-runtime-dockerhub-mirror/((image_repository))
    username: _json_key
    password: ((gcp-tas-runtime-service-account/config-json))
    tag: ((image_tag))

inputs:
- name: ci
- name: repo

outputs:
- name: built-binaries

params:
  DEFAULT_PARAMS:
  FUNCTIONS:
  ENVS:
  MAPPING:

run:
  path: ci/shared/tasks/build-binaries/task.bash
