---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((image_repository))
    tag: ((image_tag))

inputs:
- name: ci
- name: repo

outputs:
- name: built-binaries

params:
  DEFAULT_PARAMS:
  FUNCTIONS:
  ENVS:
  MAPPING:

run:
  path: ci/shared/tasks/build-binaries/task.bash
