---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: us-central1-docker.pkg.dev/cf-diego-pivotal/tas-runtime-dockerhub-mirror/cloudfoundry/grace
    username: _json_key
    password: ((gcp-tas-runtime-service-account/config-json))
    tag: ((image_tag))

inputs:
- name: ci
- name: repo

outputs:
- name: copied-grace-opsfile

params:
run:
  path: /bin/sh
  args:
  - -exc
  - |
    cp /grace-opsfile.yml ./copied-grace-opsfile/
