---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/grace
    tag: ((image_tag))

inputs:
- name: ci
- name: repo

outputs:
- name: copied-grace-opsfile

params:
run:
  path: /bin/sh
  args:
  - -exc
  - |
    cp /grace-opsfile.yml ./copied-grace-opsfile/
