---
platform: linux

inputs:
  - name: ci
  - name: repo
  - name: previous-github-release
  - name: version
  - name: released-binaries
    optional: true
  - name: extra-metadata
    optional: true

outputs:
  - name: built-release-notes

params:
  BOSH_IO_ORG: cloudfoundry
  GITHUB_ORG:  cloudfoundry

run:
  path: ci/shared/tasks/build-release-notes/task.bash
