---
platform: linux

inputs:
  - name: ci
  - name: source-branch
  - name: onto-branch

outputs:
  - name: merged-branch

params:
  SOURCE_BRANCH_NAME:
  ONTO_BRANCH_NAME:

run:
  path: ci/shared/tasks/git-merge-branches/task.bash
