---
readme: |
  This task bumps Gemfile dependencies for a Ruby project using bundler.
oses:
  - linux
params:
  GEMFILES: Multiline list of paths to Gemfiles relative to the repo root. e.g. Gemfile
  ENVS: |
    (Currently works on Linux Only). This parameter defines a list of environment variables will be loaded at runtime, as opposed to
    container-creation time. The purpose here is to allow users to extend the list of environment
    variables used by the task simply by updating the pipeline config, rather than by updating the task definition
    in linux.yml.
