---
platform: windows

inputs:
- name: ci
- name: version

outputs:
- name: built-metadata

run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - ci/windows2016fs/tasks/build-rootfs-metadata/run.ps1
